[PHP]
; Maksimalna velicina upload fajla
upload_max_filesize = 100M
post_max_size = 100M

; Maksimalno vrijeme izvrsavanja PHP skripte (u sekundama)
max_execution_time = 300

; Maksimalna kolicina memorije
memory_limit = 512M

; Timezone
date.timezone = Europe/Belgrade

; Prikaz gresaka (u produkciji postaviti na Off)
display_errors = Off
log_errors = On
